import { computed, Component, input } from '@angular/core';
import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeAlert,
  BadgeCheck,
  BadgeDollarSign,
  BadgePercent,
  Bell,
  BriefcaseBusiness,
  Calendar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheckBig,
  CircleDollarSign,
  CircleUserRound,
  CopyCheck,
  CreditCard,
  ExternalLink,
  Eye,
  Gift,
  Grid2x2,
  HandHelping,
  Headset,
  Heart,
  House,
  Image,
  LayoutDashboard,
  LifeBuoy,
  List,
  Lock,
  LucideIconData,
  Mail,
  MapPin,
  Menu,
  MessageCircleMore,
  Minus,
  Package,
  PackageCheck,
  PackageOpen,
  Pencil,
  Phone,
  Plus,
  ReceiptText,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  Trash2,
  Truck,
  Upload,
  Wallet,
  X,
  LucideAngularModule
} from 'lucide-angular';

const ICONS: Record<string, LucideIconData> = {
  alert: CircleAlert,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  bag: ShoppingBag,
  bell: Bell,
  'badge-alert': BadgeAlert,
  'badge-check': BadgeCheck,
  'badge-dollar': BadgeDollarSign,
  'badge-percent': BadgePercent,
  briefcase: BriefcaseBusiness,
  calendar: Calendar,
  chart: ChartColumn,
  check: Check,
  'circle-check': CircleCheckBig,
  'circle-dollar': CircleDollarSign,
  'copy-check': CopyCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  card: CreditCard,
  dashboard: LayoutDashboard,
  edit: Pencil,
  external: ExternalLink,
  eye: Eye,
  gift: Gift,
  filters: SlidersHorizontal,
  grid: Grid2x2,
  hand: HandHelping,
  headset: Headset,
  heart: Heart,
  home: House,
  image: Image,
  life: LifeBuoy,
  list: List,
  lock: Lock,
  mail: Mail,
  map: MapPin,
  menu: Menu,
  message: MessageCircleMore,
  minus: Minus,
  package: Package,
  'package-check': PackageCheck,
  'package-open': PackageOpen,
  phone: Phone,
  plus: Plus,
  receipt: ReceiptText,
  search: Search,
  settings: Settings,
  share: Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  truck: Truck,
  trash: Trash2,
  upload: Upload,
  user: CircleUserRound,
  wallet: Wallet,
  x: X
};

@Component({
  selector: 'app-icon',
  standalone: true,
  imports: [LucideAngularModule],
  template: `
    <lucide-icon
      [img]="resolvedIcon()"
      [size]="size()"
      [strokeWidth]="strokeWidth()"
      [class]="className()"
    />
  `
})
export class IconComponent {
  readonly name = input<string>('search');
  readonly size = input(18);
  readonly strokeWidth = input(1.75);
  readonly className = input('text-white');

  readonly resolvedIcon = computed(() => ICONS[this.name()] ?? Search);
}
