spring.datasource.url=${SHOPFLOW_DB_URL:jdbc:postgresql://localhost:5432/shopflow}
spring.datasource.username=${SHOPFLOW_DB_USERNAME:shopflow}
spring.datasource.password=${SHOPFLOW_DB_PASSWORD:shopflow}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
