spring.datasource.url=${SHOPFLOW_DB_URL:jdbc:mysql://localhost:3306/shopflow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SHOPFLOW_DB_USERNAME:root}
spring.datasource.password=${SHOPFLOW_DB_PASSWORD:}

spring.h2.console.enabled=false
