server.port=9090

spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

shopflow.jwt.secret=c2hvcGZsb3ctc2VjdXJlLWFjY2Vzcy1hbmQtcmVmcmVzaC10b2tlbi1rZXk=
shopflow.jwt.expiration=3600000
shopflow.jwt.refreshExpiration=604800000

spring.application.name=shopflow-backend
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.default-produces-media-type=application/json
